prj_cesar/prj_cesar/urls.py
from django.conf.urls import url
from cesar_app.views import index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', index, name='index')
]

prj_cesar/cesar_app/models.py
from django.db import models


class Word(models.Model):
    """ Model for word base

    """

    name = models.CharField(
        max_length=128,
        blank=False,
        verbose_name="Word's name",
    )

    def __str__(self):
        return '{0}'.format(self.name)

prj_cesar/cesar_app/forms.py
from django import forms


class SampleForm(forms.Form):
    """Form text and shift

    """
    text = forms.CharField(
        label='Text',
        max_length=512,
        widget=forms.Textarea(attrs={
            'placeholder': 'Enter your text',
            'class': 'form-control',
            'cols': 10,
            'rows': 10,
            'style': 'resize:none;'
        })
    )

    shift = forms.CharField(
        label='Shift',
        max_length=8,
        widget=forms.NumberInput(attrs={
            'value': '3',
            'class': 'form-control',
            'style': 'width:80px;'
        })
    )

prj_cesar/cesar_app/views.py
# Django
from django.shortcuts import render, HttpResponse

# Forms
from cesar_app.forms import SampleForm

# local constants and functions
from cesar_app.somedata import crypt, encrypt, count, find_key

# standard python library
import re
import json


def index(request):
    """
    Caesar cipher. Draws and takes 2 fields for processing:
    text and shift. It allows you to crypt or encrypt text
    using the shift. The output sends the encrypted or crypted
    text. Just go count the number of incoming letters and
    it is checked whether or not the encrypted code.
    """
    if request.POST and request.is_ajax():
        text = request.POST['text'].strip().lower()  # incoming text
        shift = int(request.POST['shift']) % 25  # incoming shift
        regex = re.search(r'[^a-zA-Z \',.:"?!]', text)  # check regex
        output = ''  # text to be output
        cnt = {}  # count letters
        data = {}  # output data
        say = ''  # response determination test

        if not regex and text != '':
            if 'crypt' == request.POST['name']:
                output = crypt(text, shift)  # decoding text
                cnt = sorted(count(text))  # a list of the number of characters
            elif 'encrypt' == request.POST['name']:
                output = encrypt(text, shift)  # coding text
                cnt = sorted(count(text))  # a list of the number of characters
            elif 'auto' == request.POST['name']:
                list_text = text.split()  # split the text into a list
                if len(list_text) >= 1:
                    cnt = sorted(count(text))  # a list of the number of characters
                    say = find_key(list_text)  # response determination test

        else:
            if regex:
                output = 'error regex: {0}'.format(regex.string)  # gives regex error
            elif text == '':
                output = 'Text is empty'  # gives empty error

        data['cnt'] = cnt
        data['say'] = say
        data['text'] = output
        data['cnt'] = cnt
        data = json.dumps(data)  # packaging to json

        return HttpResponse(data, content_type='application/json')

    else:
        form = SampleForm()  # drawing form
        return render(request, 'index.html', {'form': form})

prj_cesar/templates/base.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}{% endblock %}
    </title>

    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <script src={% static "js/bootstrap.min.js" %}></script>
    <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>

</head>
<body>

{% block content %}{% endblock content %}


</body>
</html>

prj_cesar/templates/index.html
{% extends 'base.html' %}
{% block title %}Caesar cipher{% endblock %}
{% block content %}

<script>

function graf(json) {
    $('#container').highcharts({
        chart: {
            type: 'column'
        },
        title: {
            text: 'Count alphabet'
        },
        subtitle: {
        },
        xAxis: {
            type: 'category',
            labels: {
                rotation: -45,
                style: {
                    fontSize: '13px',
                    fontFamily: 'Verdana, sans-serif'
                }
            }
        },
        yAxis: {
            min: 0,
            title: {
                text: 'count'
            }
        },
        legend: {
            enabled: false
        },
        tooltip: {
            pointFormat: ''
        },
        series: [{
            name: 'Values',
            data: json,
            dataLabels: {
                enabled: true,
                rotation: -90,
                color: '#FFFFFF',
                align: 'right',
                format: '{point.y:.1f}', // one decimal
                y: 10, // 10 pixels down from the top
                style: {
                    fontSize: '13px',
                    fontFamily: 'Verdana, sans-serif'
                }
            }
        }]
    });
};
<!-- END hightcharts data-->

<!-- Ajax, sending data to views -->
$( document ).ready(function() {
$('.btn-clic').click(function(event){
    event.preventDefault();
    $.ajax({
            url: '/',
            type: "POST",
            dataType: 'json',
            data: {csrfmiddlewaretoken: '{{ csrf_token }}', text : $('#id_text').val(), shift:$("#id_shift").val(), name: $(this).attr('name')},
            success: function (data) {
                $('#output').val(data.text);
                graf(data.cnt)
            }
});});
    $('#id_text').on('input', function () {
        $.ajax({
            url: '/',
            type: "POST",
            dataType: 'json',
            data: {csrfmiddlewaretoken: '{{ csrf_token }}', text : $('#id_text').val(), shift: '0', name: 'auto'},
            success: function (data) {
                $('#output').val(data.text);
                graf(data.cnt);
                $('#say').text(data.say);
            }
});
    })
});
<!-- END Ajax, sending data to views -->

</script>

<div class="container">
        <h3 class="muted">Caesar cipher</h3>
        <hr>
    <div class="row justify-content-md-center">

    <form action="/" method="post" class="">
    {% csrf_token %}

    <div class="col-sm-5 col-md-auto">
        <div class="form-group">
            <label>{{ form.text.label }}</label>
            {{ form.text }}
        </div>
    </div>


    <div class="col-sm-2 col-md-auto">
        <div class="form-group">
            <label>{{ form.shift.label }}</label>
            {{ form.shift }}
        </div>

        <div class="form-group">
            <button type="button" class="btn btn-default btn-clic" id="crypt" name="crypt" value="crypt">Crypt</button>
            <button type="button" class="btn btn-default btn-clic" id="encrypt" name="encrypt" value="encrypt">Encrypt</button>
        </div>
    </div>


    <div class="col-sm-5 col-md-auto">
        <div class="form-group">
           <label>Output</label>
           <textarea id="output" class="form-control" readonly cols="10" maxlength="512" rows="10" style="resize: none"></textarea>
        </div>
    </div>
    </form>

    <br>

    </div>

    <br>

    <div class="row">
        <div id="container" class="col-sm-12" style="min-width: 300px; height: 260px; margin: 0 auto"></div>
    </div>

    <br>

    <div class="row">
        <div class="col-sm-12"><p class="bg-info" id="say"></p></div>
    </div>

</div>

{% endblock content %}